#include "global.h"
#include "evolution_stages.h"
#include "constants/species.h"

const u16 gStage1EvoMons[] = {
    // Gen 1
    SPECIES_BULBASAUR, SPECIES_CHARMANDER, SPECIES_SQUIRTLE, SPECIES_CATERPIE, SPECIES_WEEDLE,
    SPECIES_PIDGEY, SPECIES_RATTATA, SPECIES_SPEAROW, SPECIES_EKANS, SPECIES_SANDSHREW,
    SPECIES_NIDORAN_F, SPECIES_NIDORAN_M, SPECIES_CLEFAIRY, SPECIES_VULPIX, SPECIES_JIGGLYPUFF,
    SPECIES_ZUBAT, SPECIES_ODDISH, SPECIES_PARAS, SPECIES_VENONAT, SPECIES_DIGLETT,
    SPECIES_MEOWTH, SPECIES_PSYDUCK, SPECIES_MANKEY, SPECIES_GROWLITHE, SPECIES_POLIWAG,
    SPECIES_ABRA, SPECIES_MACHOP, SPECIES_BELLSPROUT, SPECIES_TENTACOOL, SPECIES_GEODUDE,
    SPECIES_PONYTA, SPECIES_SLOWPOKE, SPECIES_MAGNEMITE, SPECIES_FARFETCHD, SPECIES_DODUO,
    SPECIES_SEEL, SPECIES_GRIMER, SPECIES_SHELLDER, SPECIES_GASTLY, SPECIES_ONIX,
    SPECIES_DROWZEE, SPECIES_KRABBY, SPECIES_VOLTORB, SPECIES_CUBONE, SPECIES_KOFFING,
    SPECIES_RHYHORN, SPECIES_CHANSEY, SPECIES_TANGELA, SPECIES_KANGASKHAN, SPECIES_HORSEA,
    SPECIES_GOLDEEN, SPECIES_STARYU, SPECIES_MR_MIME, SPECIES_SCYTHER, SPECIES_PINSIR,
    SPECIES_TAUROS, SPECIES_MAGIKARP, SPECIES_LAPRAS, SPECIES_DITTO, SPECIES_EEVEE,
    SPECIES_PORYGON, SPECIES_OMANYTE, SPECIES_KABUTO, SPECIES_AERODACTYL, SPECIES_DRATINI,

    // Gen 2
    SPECIES_CHIKORITA, SPECIES_CYNDAQUIL, SPECIES_TOTODILE, SPECIES_SENTRET, SPECIES_HOOTHOOT,
    SPECIES_LEDYBA, SPECIES_SPINARAK, SPECIES_CHINCHOU, SPECIES_PICHU, SPECIES_CLEFFA,
    SPECIES_IGGLYBUFF, SPECIES_TOGEPI, SPECIES_NATU, SPECIES_MAREEP, SPECIES_HOPPIP,
    SPECIES_AIPOM, SPECIES_SUNKERN, SPECIES_WOOPER, SPECIES_MURKROW, SPECIES_MISDREAVUS,
    SPECIES_UNOWN, SPECIES_GIRAFARIG, SPECIES_DUNSPARCE, SPECIES_SNUBBULL, SPECIES_QWILFISH,
    SPECIES_SHUCKLE, SPECIES_HERACROSS, SPECIES_SNEASEL, SPECIES_TEDDIURSA, SPECIES_SLUGMA,
    SPECIES_SWINUB, SPECIES_CORSOLA, SPECIES_REMORAID, SPECIES_DELIBIRD, SPECIES_MANTINE,
    SPECIES_SKARMORY, SPECIES_HOUNDOUR, SPECIES_PHANPY, SPECIES_STANTLER, SPECIES_SMEARGLE,
    SPECIES_TYROGUE, SPECIES_MILTANK, SPECIES_LARVITAR, SPECIES_MANTYKE,

    // Gen 3
    SPECIES_TREECKO, SPECIES_TORCHIC, SPECIES_MUDKIP, SPECIES_POOCHYENA, SPECIES_ZIGZAGOON,
    SPECIES_WURMPLE, SPECIES_LOTAD, SPECIES_SEEDOT, SPECIES_TAILLOW, SPECIES_WINGULL,
    SPECIES_RALTS, SPECIES_SURSKIT, SPECIES_SHROOMISH, SPECIES_SLAKOTH, SPECIES_NINCADA,
    SPECIES_WHISMUR, SPECIES_MAKUHITA, SPECIES_AZURILL, SPECIES_NOSEPASS, SPECIES_SKITTY,
    SPECIES_ARON, SPECIES_MEDITITE, SPECIES_ELECTRIKE, SPECIES_PLUSLE, SPECIES_MINUN,
    SPECIES_VOLBEAT, SPECIES_ILLUMISE, SPECIES_ROSELIA, SPECIES_GULPIN, SPECIES_CARVANHA,
    SPECIES_NUMEL, SPECIES_TORKOAL, SPECIES_SPOINK, SPECIES_SPINDA, SPECIES_TRAPINCH,
    SPECIES_CACNEA, SPECIES_SWABLU, SPECIES_ZANGOOSE, SPECIES_SEVIPER, SPECIES_BARBOACH,
    SPECIES_CORPHISH, SPECIES_BALTOY, SPECIES_LILEEP, SPECIES_ANORITH, SPECIES_FEEBAS,
    SPECIES_SHUPPET, SPECIES_DUSKULL, SPECIES_CLAMPERL, SPECIES_ABSOL, SPECIES_WYNAUT,
    SPECIES_SNORUNT, SPECIES_BAGON, SPECIES_BELDUM, SPECIES_CASTFORM, SPECIES_KECLEON,
    SPECIES_CHIMECHO,

    // Gen 4
    SPECIES_TURTWIG, SPECIES_CHIMCHAR, SPECIES_PIPLUP, SPECIES_STARLY, SPECIES_BIDOOF,
    SPECIES_KRICKETOT, SPECIES_SHINX, SPECIES_CRANIDOS, SPECIES_SHIELDON, SPECIES_BURMY,
    SPECIES_COMBEE, SPECIES_PACHIRISU, SPECIES_BUIZEL, SPECIES_SHELLOS, SPECIES_DRIFLOON,
    SPECIES_BUNEARY, SPECIES_GLAMEOW, SPECIES_STUNKY, SPECIES_BRONZOR, SPECIES_CHINGLING,
    SPECIES_BONSLY, SPECIES_MIME_JR, SPECIES_HAPPINY, SPECIES_CHATOT, SPECIES_SPIRITOMB,
    SPECIES_GIBLE, SPECIES_RIOLU, SPECIES_HIPPOPOTAS, SPECIES_SKORUPI, SPECIES_CROAGUNK,
    SPECIES_FINNEON, SPECIES_SNOVER, SPECIES_ROTOM, SPECIES_CARNIVINE,

    // Gen 5
    SPECIES_SNIVY, SPECIES_TEPIG, SPECIES_OSHAWOTT, SPECIES_PATRAT, SPECIES_LILLIPUP,
    SPECIES_PURRLOIN, SPECIES_PANSAGE, SPECIES_PANSEAR, SPECIES_PANPOUR, SPECIES_MUNNA,
    SPECIES_PIDOVE, SPECIES_BLITZLE, SPECIES_ROGGENROLA, SPECIES_DRILBUR, SPECIES_AUDINO,
    SPECIES_TIMBURR, SPECIES_TYMPOLE, SPECIES_SEWADDLE, SPECIES_VENIPEDE, SPECIES_COTTONEE,
    SPECIES_PETILIL, SPECIES_BASCULIN, SPECIES_SANDILE, SPECIES_DARUMAKA, SPECIES_SCRAGGY,
    SPECIES_ZORUA, SPECIES_GOTHITA, SPECIES_SOLOSIS, SPECIES_VANILLITE, SPECIES_DEERLING,
    SPECIES_EMOLGA, SPECIES_KARRABLAST, SPECIES_FOONGUS, SPECIES_FERROSEED, SPECIES_KLINK,
    SPECIES_TYNAMO, SPECIES_LITWICK, SPECIES_AXEW, SPECIES_CUBCHOO, SPECIES_CRYOGONAL,
    SPECIES_SHELMET, SPECIES_BOUFFALANT, SPECIES_RUFFLET, SPECIES_LARVESTA, SPECIES_HEATMOR,
    SPECIES_DURANT, SPECIES_SAWK, SPECIES_THROH, SPECIES_MARACTUS, SPECIES_SIGILYPH,
    SPECIES_YAMASK, SPECIES_ALOMOMOLA, SPECIES_JOLTIK, SPECIES_FRILLISH,

    // Gen 6
    SPECIES_CHESPIN, SPECIES_FENNEKIN, SPECIES_FROAKIE, SPECIES_BUNNELBY, SPECIES_FLETCHLING,
    SPECIES_SCATTERBUG, SPECIES_LITLEO, SPECIES_FLABEBE, SPECIES_SKIDDO, SPECIES_PANCHAM,
    SPECIES_FURFROU, SPECIES_ESPURR, SPECIES_HONEDGE, SPECIES_SPRITZEE, SPECIES_SWIRLIX,
    SPECIES_INKAY, SPECIES_BINACLE, SPECIES_SKRELP, SPECIES_CLAUNCHER, SPECIES_HELIOPTILE,
    SPECIES_TYRUNT, SPECIES_AMAURA, SPECIES_DEDENNE, SPECIES_CARBINK, SPECIES_GOOMY,
    SPECIES_PHANTUMP, SPECIES_PUMPKABOO, SPECIES_BERGMITE, SPECIES_NOIBAT,

    // Gen 7
    SPECIES_ROWLET, SPECIES_LITTEN, SPECIES_POPPLIO, SPECIES_PIKIPEK, SPECIES_YUNGOOS,
    SPECIES_GRUBBIN, SPECIES_CRABRAWLER, SPECIES_ORICORIO, SPECIES_CUTIEFLY, SPECIES_ROCKRUFF,
    SPECIES_WISHIWASHI, SPECIES_MAREANIE, SPECIES_DEWPIDER, SPECIES_FOMANTIS, SPECIES_MORELULL,
    SPECIES_SALANDIT, SPECIES_STUFFUL, SPECIES_BOUNSWEET, SPECIES_COMFEY, SPECIES_ORANGURU,
    SPECIES_PASSIMIAN, SPECIES_WIMPOD, SPECIES_MINIOR, SPECIES_KOMALA, SPECIES_TURTONATOR,
    SPECIES_TOGEDEMARU, SPECIES_MIMIKYU, SPECIES_BRUXISH, SPECIES_DRAMPA, SPECIES_DHELMISE,
    SPECIES_JANGMO_O,

    // Gen 8
    SPECIES_GROOKEY, SPECIES_SCORBUNNY, SPECIES_SOBBLE, SPECIES_SKWOVET, SPECIES_ROOKIDEE,
    SPECIES_BLIPBUG, SPECIES_NICKIT, SPECIES_WOOLOO, SPECIES_CHEWTLE,
    SPECIES_YAMPER, SPECIES_ROLYCOLY, SPECIES_APPLIN, SPECIES_SILICOBRA, SPECIES_CRAMORANT,
    SPECIES_ARROKUDA, SPECIES_TOXEL, SPECIES_SNOM, SPECIES_STONJOURNER, SPECIES_EISCUE,
    SPECIES_DURALUDON, SPECIES_DREEPY, SPECIES_INDEEDEE, SPECIES_MORPEKO, SPECIES_PINCURCHIN,
    SPECIES_GOSSIFLEUR, SPECIES_SINISTEA, SPECIES_HATENNA, SPECIES_IMPIDIMP, SPECIES_MILCERY,
    SPECIES_FALINKS, SPECIES_SIZZLIPEDE, SPECIES_CLOBBOPUS, SPECIES_RUNERIGUS, SPECIES_KUBFU,
    SPECIES_SINISTCHA,

    // Gen 9
    SPECIES_SPRIGATITO, SPECIES_FUECOCO, SPECIES_QUAXLY, SPECIES_LECHONK, SPECIES_TAROUNTULA,
    SPECIES_NYMBLE, SPECIES_KLAWF, SPECIES_CAPSAKID, SPECIES_TADBULB, SPECIES_WATTREL,
    SPECIES_MASCHIFF, SPECIES_SHROODLE, SPECIES_FIDOUGH, SPECIES_WOOPER_PALDEA, SPECIES_CETODDLE,
    SPECIES_FRIGIBAX, SPECIES_TINKATINK, SPECIES_CHARCADET, SPECIES_TOEDSCOOL, SPECIES_BRAMBLIN,
    SPECIES_GIMMIGHOUL_CHEST, SPECIES_GIMMIGHOUL_ROAMING, SPECIES_GREAVARD, SPECIES_FLAMIGO,
    SPECIES_CYCLIZAR, SPECIES_PAWMI, SPECIES_DONDOZO, SPECIES_TATSUGIRI, SPECIES_VAROOM,
};

const u16 gStage2EvoMons[] = {
    // Gen 1
    SPECIES_IVYSAUR, SPECIES_CHARMELEON, SPECIES_WARTORTLE, SPECIES_METAPOD, SPECIES_KAKUNA,
    SPECIES_PIDGEOTTO, SPECIES_RATICATE, SPECIES_FEAROW, SPECIES_ARBOK, SPECIES_SANDSLASH,
    SPECIES_NIDORINA, SPECIES_NIDORINO, SPECIES_NINETALES, SPECIES_WIGGLYTUFF, SPECIES_GOLBAT,
    SPECIES_GLOOM, SPECIES_POLIWHIRL, SPECIES_KADABRA, SPECIES_MACHOKE, SPECIES_WEEPINBELL,
    SPECIES_TENTACRUEL, SPECIES_GRAVELER, SPECIES_RAPIDASH, SPECIES_MAGNETON, SPECIES_DODRIO,
    SPECIES_DEWGONG, SPECIES_MUK, SPECIES_CLOYSTER, SPECIES_HYPNO, SPECIES_KINGLER,
    SPECIES_ELECTRODE, SPECIES_MAROWAK, SPECIES_WEEZING, SPECIES_LICKITUNG, SPECIES_SEADRA,
    SPECIES_SEAKING, SPECIES_STARMIE, SPECIES_JYNX, SPECIES_ELECTABUZZ, SPECIES_MAGMAR,
    SPECIES_VAPOREON, SPECIES_JOLTEON, SPECIES_FLAREON, SPECIES_PORYGON, SPECIES_OMASTAR,
    SPECIES_KABUTOPS, SPECIES_DRAGONAIR,

    // Gen 2
    SPECIES_BAYLEEF, SPECIES_QUILAVA, SPECIES_CROCONAW, SPECIES_FURRET, SPECIES_NOCTOWL,
    SPECIES_LEDIAN, SPECIES_ARIADOS, SPECIES_LANTURN, SPECIES_XATU, SPECIES_FLAAFFY,
    SPECIES_JUMPLUFF, SPECIES_AMBIPOM, SPECIES_SUNFLORA, SPECIES_QUAGSIRE, SPECIES_MURKROW,
    SPECIES_MISDREAVUS, SPECIES_GIRAFARIG, SPECIES_DUNSPARCE, SPECIES_GRANBULL, SPECIES_QWILFISH,
    SPECIES_SCIZOR, SPECIES_URSARING, SPECIES_MAGCARGO, SPECIES_PILOSWINE, SPECIES_OCTILLERY,
    SPECIES_HOUNDOOM, SPECIES_DONPHAN, SPECIES_PORYGON2, SPECIES_PUPITAR,

    // Gen 3
    SPECIES_GROVYLE, SPECIES_COMBUSKEN, SPECIES_MARSHTOMP, SPECIES_MIGHTYENA, SPECIES_LINOONE,
    SPECIES_SILCOON, SPECIES_CASCOON, SPECIES_LOMBRE, SPECIES_NUZLEAF, SPECIES_SWELLOW,
    SPECIES_PELIPPER, SPECIES_KIRLIA, SPECIES_MASQUERAIN, SPECIES_BRELOOM, SPECIES_VIGOROTH,
    SPECIES_NINJASK, SPECIES_LOUDRED, SPECIES_HARIYAMA, SPECIES_PROBOPASS, SPECIES_LAIRON,
    SPECIES_MEDICHAM, SPECIES_MANECTRIC, SPECIES_SHARPEDO, SPECIES_CAMERUPT, SPECIES_GRUMPIG,
    SPECIES_VIBRAVA, SPECIES_CACTURNE, SPECIES_ALTARIA, SPECIES_WHISCASH, SPECIES_CRAWDAUNT,
    SPECIES_CLAYDOL, SPECIES_CRADILY, SPECIES_ARMALDO, SPECIES_MILOTIC, SPECIES_BANETTE,
    SPECIES_DUSCLOPS, SPECIES_WALREIN, SPECIES_HUNTAIL, SPECIES_GOREBYSS, SPECIES_SHELGON,
    SPECIES_METANG,

    // Gen 4
    SPECIES_GROTLE, SPECIES_MONFERNO, SPECIES_PRINPLUP, SPECIES_STARAVIA, SPECIES_BIBAREL,
    SPECIES_KRICKETUNE, SPECIES_LUXIO, SPECIES_RAMPARDOS, SPECIES_BASTIODON, SPECIES_WORMADAM,
    SPECIES_MOTHIM, SPECIES_VESPIQUEN, SPECIES_FLOATZEL, SPECIES_GASTRODON, SPECIES_DRIFBLIM,
    SPECIES_LOPUNNY, SPECIES_PURUGLY, SPECIES_SKUNTANK, SPECIES_BRONZONG, SPECIES_GABITE,
    SPECIES_LUCARIO, SPECIES_HIPPOWDON, SPECIES_DRAPION, SPECIES_TOXICROAK, SPECIES_LUMINEON,
    SPECIES_ABOMASNOW, SPECIES_WEAVILE, SPECIES_MAGMORTAR, SPECIES_ELECTIVIRE, SPECIES_TOGEKISS,
    SPECIES_GLISCOR, SPECIES_PROBOPASS, SPECIES_MAMOSWINE, SPECIES_LICKILICKY, SPECIES_TANGROWTH,

    // Gen 5
    SPECIES_SERVINE, SPECIES_PIGNITE, SPECIES_DEWOTT, SPECIES_WATCHOG, SPECIES_HERDIER,
    SPECIES_LIEPARD, SPECIES_SIMISAGE, SPECIES_SIMISEAR, SPECIES_SIMIPOUR, SPECIES_MUSHARNA,
    SPECIES_TRANQUILL, SPECIES_ZEBSTRIKA, SPECIES_BOLDORE, SPECIES_EXCADRILL, SPECIES_GURDURR,
    SPECIES_PALPITOAD, SPECIES_SWADLOON, SPECIES_WHIRLIPEDE, SPECIES_WHIMSICOTT, SPECIES_LILLIGANT,
    SPECIES_KROKOROK, SPECIES_SCRAFTY, SPECIES_ZOROARK, SPECIES_GOTHITELLE, SPECIES_REUNICLUS,
    SPECIES_SAWSBUCK, SPECIES_ESCAVALIER, SPECIES_FERROTHORN, SPECIES_KLANG, SPECIES_EELEKTRIK,
    SPECIES_LAMPENT, SPECIES_FRAXURE, SPECIES_BEARTIC, SPECIES_ACCELGOR, SPECIES_MANDIBUZZ,
    SPECIES_PORYGON_Z,

    // Gen 6
    SPECIES_QUILLADIN, SPECIES_BRAIXEN, SPECIES_FROGADIER, SPECIES_DIGGERSBY, SPECIES_FLETCHINDER,
    SPECIES_SPEWPA, SPECIES_PYROAR, SPECIES_FLORGES, SPECIES_GOGOAT, SPECIES_PANGORO,
    SPECIES_MEOWSTIC, SPECIES_DOUBLADE, SPECIES_AROMATISSE, SPECIES_SLURPUFF, SPECIES_MALAMAR,
    SPECIES_BARBARACLE, SPECIES_DRAGALGE, SPECIES_CLAWITZER, SPECIES_HELIOLISK, SPECIES_TYRANTRUM,
    SPECIES_AURORUS, SPECIES_SLIGGOO, SPECIES_TREVENANT, SPECIES_GOURGEIST, SPECIES_AVALUGG,
    SPECIES_NOIVERN,

    // Gen 7
    SPECIES_DARTRIX, SPECIES_TORRACAT, SPECIES_BRIONNE, SPECIES_TRUMBEAK, SPECIES_GUMSHOOS,
    SPECIES_CHARJABUG, SPECIES_CRABOMINABLE, SPECIES_RIBOMBEE, SPECIES_LYCANROC, SPECIES_TOXAPEX,
    SPECIES_ARAQUANID, SPECIES_LURANTIS, SPECIES_SHIINOTIC, SPECIES_SALAZZLE, SPECIES_BEWEAR,
    SPECIES_TSAREENA, SPECIES_GOLISOPOD, SPECIES_HAKAMO_O,

    // Gen 8
    SPECIES_THWACKEY, SPECIES_RABOOT, SPECIES_DRIZZILE, SPECIES_GREEDENT, SPECIES_CORVISQUIRE,
    SPECIES_DOTTLER, SPECIES_THIEVUL, SPECIES_ELDEGOSS, SPECIES_DUBWOOL, SPECIES_DREDNAW,
    SPECIES_BOLTUND, SPECIES_COALOSSAL, SPECIES_FLAPPLE, SPECIES_APPLETUN, SPECIES_SANDACONDA,
    SPECIES_CRAMORANT, SPECIES_BARRASKEWDA, SPECIES_ARCTOZOLT, SPECIES_DRACOVISH, SPECIES_DRACOZOLT,
    SPECIES_DRAGAPULT, SPECIES_SINISTEA, SPECIES_HATTERENE, SPECIES_GRIMMSNARL, SPECIES_ALCREMIE,
    SPECIES_COPPERAJAH, SPECIES_DURALUDON, SPECIES_ZARUDE, SPECIES_URSHIFU_SINGLE_STRIKE,
    SPECIES_URSHIFU_RAPID_STRIKE,

    // Gen 9
    SPECIES_FLORAGATO, SPECIES_CROCALOR, SPECIES_QUAXWELL, SPECIES_OINKOLOGNE, SPECIES_SPIDOPS,
    SPECIES_ARBOLIVA, SPECIES_BELLIBOLT, SPECIES_KILOWATTREL, SPECIES_MABOSSTIFF, SPECIES_GRAFAIAI,
    SPECIES_DACHSBUN, SPECIES_CLODSIRE, SPECIES_PALAFIN, SPECIES_CETITAN, SPECIES_BRAMBLEGHAST,
    SPECIES_GOLDUCK, SPECIES_ANNIHILAPE,
};


const u16 gStage3EvoMons[] = {
    // Gen 1
    SPECIES_VENUSAUR, SPECIES_CHARIZARD, SPECIES_BLASTOISE, SPECIES_BUTTERFREE, SPECIES_BEEDRILL,
    SPECIES_PIDGEOT, SPECIES_DUGTRIO, SPECIES_ALAKAZAM, SPECIES_VILEPLUME, SPECIES_PARASECT,
    SPECIES_VENOMOTH, SPECIES_GOLDUCK, SPECIES_POLIWRATH, SPECIES_MACHAMP, SPECIES_VICTREEBEL,
    SPECIES_GOLEM, SPECIES_SNORLAX, SPECIES_DRAGONITE,

    // Gen 2
    SPECIES_MEGANIUM, SPECIES_TYPHLOSION, SPECIES_FERALIGATR, SPECIES_CROBAT, SPECIES_POLITOED,
    SPECIES_TOGETIC, SPECIES_AMPHAROS, SPECIES_SUDOWOODO, SPECIES_JUMPLUFF, SPECIES_POLITOED,
    SPECIES_UMBREON, SPECIES_ESPEON, SPECIES_SLOWKING, SPECIES_STEELIX, SPECIES_SCIZOR,
    SPECIES_KINGDRA, SPECIES_TYRANITAR, SPECIES_BLISSEY,

    // Gen 3
    SPECIES_SCEPTILE, SPECIES_BLAZIKEN, SPECIES_SWAMPERT, SPECIES_EXPLOUD, SPECIES_SHIFTRY,
    SPECIES_LUDICOLO, SPECIES_GARDEVOIR, SPECIES_SLAKING, SPECIES_AGGRON, SPECIES_MANECTRIC,
    SPECIES_FLYGON, SPECIES_CRADILY, SPECIES_ARMALDO, SPECIES_SALAMENCE, SPECIES_METAGROSS,

    // Gen 4
    SPECIES_TORTERRA, SPECIES_INFERNAPE, SPECIES_EMPOLEON, SPECIES_STARAPTOR, SPECIES_LUXRAY,
    SPECIES_HONCHKROW, SPECIES_MISMAGIUS, SPECIES_GARCHOMP, SPECIES_MAMOSWINE, SPECIES_FROSLASS,
    SPECIES_LEAFEON, SPECIES_GLACEON, SPECIES_YANMEGA, SPECIES_MAGNEZONE, SPECIES_DUSKNOIR,

    // Gen 5
    SPECIES_SERPERIOR, SPECIES_EMBOAR, SPECIES_SAMUROTT, SPECIES_UNFEZANT, SPECIES_GIGALITH,
    SPECIES_CONKELDURR, SPECIES_SEISMITOAD, SPECIES_LEAVANNY, SPECIES_SCOLIPEDE, SPECIES_CHANDELURE,
    SPECIES_HAXORUS, SPECIES_HYDREIGON, SPECIES_VOLCARONA, SPECIES_VANILLUXE,

    // Gen 6
    SPECIES_CHESNAUGHT, SPECIES_DELPHOX, SPECIES_GRENINJA, SPECIES_TALONFLAME, SPECIES_VIVILLON,
    SPECIES_AEGISLASH, SPECIES_GOODRA,

    // Gen 7
    SPECIES_DECIDUEYE, SPECIES_INCINEROAR, SPECIES_PRIMARINA, SPECIES_TOUCANNON, SPECIES_VIKAVOLT,
    SPECIES_KOMMO_O,

    // Gen 8
    SPECIES_RILLABOOM, SPECIES_CINDERACE, SPECIES_INTELEON, SPECIES_CORVIKNIGHT, SPECIES_ORBEETLE,
    SPECIES_TOXTRICITY, SPECIES_CENTISKORCH, SPECIES_HATTERENE, SPECIES_GRIMMSNARL, SPECIES_DRAGAPULT,

    // Gen 9
    SPECIES_MEOWSCARADA, SPECIES_SKELEDIRGE, SPECIES_QUAQUAVAL, SPECIES_LOKIX, SPECIES_GARGANACL,
    SPECIES_ARCTIBAX, SPECIES_TINKATON,
};


const u32 gStage1EvoMonsCount = ARRAY_COUNT(gStage1EvoMons);

const u32 gStage2EvoMonsCount = ARRAY_COUNT(gStage2EvoMons);

const u32 gStage3EvoMonsCount = ARRAY_COUNT(gStage3EvoMons);